# Copyright 2025 Daniel Pfeifer <daniel@pfeifer-mail.de>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.

name: CI
permissions: { contents: write }

on:
  pull_request:
  push:
    tags: ['*']

jobs:
  build:
    name: "${{ matrix.toolchain.os }} (${{ matrix.toolchain.cc }}, shared: ${{ matrix.shared }})"
    runs-on: ${{ matrix.toolchain.runner }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - runner: macos-15
            os: Darwin
            cc: gcc
          - runner: ubuntu-24.04
            os: Linux
            cc: clang
          - runner: windows-2025
            os: win64
            cc: gcc
          - runner: windows-2025
            os: win64
            cc: cl
        shared:
          - ON
          - OFF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Dependencies
        shell: cmake -P {0}
        run: |
          foreach(pkg
              "https://github.com/purpleKarrot/qux/releases/download/v1.1.0/Qux-1.1.0-${{ matrix.toolchain.os }}-runtime.tar.gz"
              "https://github.com/purpleKarrot/qux/releases/download/v1.1.0/Qux-1.1.0-${{ matrix.toolchain.os }}-develop.tar.gz"
              )
            file(DOWNLOAD "${pkg}" "pkg.tgz")
            file(ARCHIVE_EXTRACT INPUT "pkg.tgz" DESTINATION prefix)
          endforeach()

      - name: Add MSVC tools to PATH (Windows)
        if: matrix.toolchain.cc == 'cl'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: >
          cmake -B build -G "Ninja Multi-Config"
          -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
          -DCMAKE_PREFIX_PATH:PATH=${{ github.workspace }}/prefix
          -DCPACK_SYSTEM_NAME:STRING=${{ matrix.toolchain.os }}-${{ matrix.toolchain.cc }}-${{ matrix.shared == 'ON' && 'shared' || 'static' }}
        env:
          CC: ${{ matrix.toolchain.cc }}

      - name: Build Release
        run: cmake --build build --config Release

      - name: Create Packages
        run: cpack -C "Release" -G TGZ
        working-directory: build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.tar.gz
